apiVersion: v1
kind: Service
metadata:
  name: static-web-app
  labels:
    app: static-web-app
spec:
  selector:
    app: static-web-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007